name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Docker Login
      env:
        USER: ${{secrets.DOCKER_USER}}
        PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $USER -p $PASSWORD
    
    - name: Build the Docker image
      run: |
        docker build -t ${{secrets.DOCKER_USER}}/docker-graphql:0.0.1 .
        docker build -t ${{secrets.DOCKER_USER}}/docker-graphql:latest .

    - name: Push the Docker Image
      run: |
        docker push ${{secrets.DOCKER_USER}}/docker-graphql:0.0.1
        docker push ${{secrets.DOCKER_USER}}/docker-graphql:latest
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag mitag:$(date +%s)
